// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.simon.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\032com.simon.dfs" +
      ".namenode.rpc\032\026NameNodeRpcModel.proto2\247\003" +
      "\n\017NameNodeService\022e\n\010register\022+.com.simo" +
      "n.dfs.namenode.rpc.RegisterRequest\032,.com" +
      ".simon.dfs.namenode.rpc.RegisterResponse" +
      "\022h\n\theartbeat\022,.com.simon.dfs.namenode.r" +
      "pc.HeartbeatRequest\032-.com.simon.dfs.name" +
      "node.rpc.HeartbeatResponse\022\\\n\005mkdir\022(.co" +
      "m.simon.dfs.namenode.rpc.MkdirRequest\032)." +
      "com.simon.dfs.namenode.rpc.MkdirResponse",
      "\022e\n\010shutdown\022+.com.simon.dfs.namenode.rp" +
      "c.ShutdownRequest\032,.com.simon.dfs.nameno" +
      "de.rpc.ShutdownResponseB6\n\"com.simon.dfs" +
      ".namenode.rpc.serviceB\016NameNodeServerP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.simon.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.simon.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
