// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.simon.dfs.namenode.rpc.model;

public interface FetchEditlogsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simon.dfs.namenode.rpc.FetchEditlogsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string editlogs = 1;</code>
   */
  String getEditlogs();
  /**
   * <code>optional string editlogs = 1;</code>
   */
  com.google.protobuf.ByteString
      getEditlogsBytes();
}
