// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.simon.dfs.namenode.rpc.model;

public interface FetchEditlogsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simon.dfs.namenode.rpc.FetchEditlogsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional int64 fetchedMaxTxid = 2;</code>
   */
  long getFetchedMaxTxid();
}
